services:
  sbg_driver:
    profiles: ["prod"]
    container_name: sbg_driver
    build:
      context: .
      dockerfile: Dockerfile.sbg_driver
      ssh:
        - default
    network_mode: host
    restart: unless-stopped
    group_add:
      - dialout
    volumes:
      - robot_shared_directory:/robot_shared_directory
      - ./settings.txt:/settings.txt:ro
      - ./sbg_driver:/robot_shared_directory/sbg_driver
      - ./data:/robot_shared_directory/data
      - /dev/sbg-device:/dev/sbg-device
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command:
      - bash
      - /launch_nodes.sh

  sbg_driver_dev:
    profiles: ["dev"]
    container_name: sbg_driver_dev
    build:
      context: .
      dockerfile: Dockerfile.sbg_driver
      ssh:
        - default
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - dialout
    restart: unless-stopped
    volumes:
      - robot_shared_directory:/robot_shared_directory
      - ./settings.txt:/settings.txt:ro
      - ./sbg_driver:/robot_shared_directory/sbg_driver
      - ./data:/robot_shared_directory/data
      - /dev/sbg-device:/dev/sbg-device
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command:
      - bash
      - /launch_nodes.sh

volumes:
  robot_shared_directory:
    external: true
